Potential BUG between Endjin.RecommendedPractices.GitHub and AF Isolated.
Corvus.Testing.AzureFunctions.ReqnRoll\Solutions\Corvus.Testing.AzureFunctions.Demo.Isolated\obj\Debug\net8.
0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFu
nctionExecutor.g.cs(10,10): error CS1001: Identifier expected

Remove unused packages and clean up project files

The project file `Corvus.Testing.AzureFunctions.Demo.Isolated.csproj` has been updated to remove the `Endjin.RecommendedPractices.GitHub` package reference along with related properties for package management. The `RestorePackagesWithLockFile` and `RestoreLockedMode` properties have also been removed, indicating a shift away from using a package lock file.

Additionally, the `packages.lock.json` file has been modified to reflect the removal of the `Endjin.RecommendedPractices.GitHub` package and its dependencies, as well as other packages like `Roslynator.Analyzers`, `StyleCop.Analyzers`, and `Microsoft.SourceLink.GitHub`. This cleanup helps streamline the project and reduce potential conflicts.